logging:
  group:
    tomcat: 
     - org.apache.catalina
     - org.apache.coyote
     - org.apache.tomcattebsdd
  level:
    root: WARN
    com:
      ruminderhub: DEBUG
    tomcat: INFODAN SELAMLAR
    

database: app_develop
